---
name: 'YAML/JSON validation against JSON Schema'
description: |
  Validates YAML or JSON file(s) against provided JSON Schema file
branding:
  icon: check-circle
  color: green
inputs:
  json-schema-file:
    description: 'JSON Schema file to validate against'
    required: true
  yaml-json-file-dir:
    description: |
      Comma separated list of YAML or JSON files and/or directories that require
      validation.
    required: true
  recursive:
    description: |
      True/False, provide True if recursive scan for YAML or JSON files
      in directory required.
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.json-schema-file }}
    - ${{ inputs.yaml-json-file-dir }}
    - ${{ inputs.recursive }}
