---
name: Self Test

'on':
  pull_request:
    branches: ['main']

jobs:
  runValidation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PyTest(s)
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pytest test/ -rxXs
      - name: Run Action (valid files)
        uses: ./
        with:
          json-schema-file: test/schema/json_schema.json
          yaml-json-file-dir: test/YAMLs/valid.json,test/JSONs/valid.json
      - name: Run Action (empty files valid)
        uses: ./
        with:
          json-schema-file: test/schema/json_schema.json
          yaml-json-file-dir: test/emptyJSONs,test/emptyYAMLSs
      - name: Run Action (check mapping)
        uses: ./
        with:
          json-schema-file: test/schema/json_schema.json
          yaml-json-file-dir: test/emptyJSONs,test/emptyYAMLSs
          schema-mapping: "test/emptyJSONs->test/schema/json_schema.json,test/emptyYAMLSs->test/schema/json_schema.json"
      - name: Run Action (check online schema + mapping)
        uses: ./
        with:
          json-schema-file: https://json-schema.org/draft-04/schema
          yaml-json-file-dir: test/schema/json_schema.json
          schema-mapping: "test/schema/json_schema.json->https://json-schema.org/draft-04/schema"
      - name: Run Action (check online schema)
        uses: ./
        with:
          json-schema-file: https://json-schema.org/draft-04/schema
          yaml-json-file-dir: test/schema/json_schema.json
