---
name: Self Test

'on':
  pull_request:
    branches: ['main']

jobs:
  runValidation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PyTest(s)
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pytest test/ -rxXs
      - name: Check YAML files inside directory
        uses: ./action.yaml
        continue-on-error: true
        with:
          json-schema-file: test/schema/json_schema.json
          yaml-file-dir: test/YAMLs/
      - name: Check JSON files inside directory
        uses: ./action.yaml
        continue-on-error: true
        with:
          json-schema-file: test/schema/json_schema.json
          yaml-file-dir: test/JSONs/
